//Choose from pdf, json, msword, msexcel, mp3, wav, audio, gif, jpeg, png, tiff, plain, xml, html, video, mpeg1, mpeg2, mpeg4, mp4, avi, mpg, chat, eaf, tar, zip, tmx
export enum CorporaMetadataFileTypeEnum {
  pdf = 'pdf',
  json = 'json',
  msword = 'msword',
  msexcel = 'msexcel',
  mp3 = 'mp3',
  wav = 'wav',
  audio = 'audio',
  gif = 'gif',
  jpeg = 'jpeg',
  png = 'png',
  tiff = 'tiff',
  plain = 'plain',
  xml = 'xml',
  html = 'html',
  video = 'video',
  mpeg1 = 'mpeg1',
  mpeg2 = 'mpeg2',
  mpeg4 = 'mpeg4',
  mp4 = 'mp4',
  avi = 'avi',
  mpg = 'mpg',
  chat = 'chat',
  eaf = 'eaf',
  tar = 'tar',
  zip = 'zip',
  tmx = 'tmx',
}
