name: unic-app
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
